spring:
  datasource:
    url: jdbc:h2:mem:jifen;DB_CLOSE_DELAY=-1;MODE=MySQL;INIT=RUNSCRIPT FROM 'classpath:init.sql'
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql

jwt:
  secret: jifen-ci-secret-key-2026
  expiration: 86400000
